Move membersList to it's own component
WomenWhoCodeCincy/WomenWhoCodeCincy.github.io pull request #43
Opened 2020-11-01 00:24 UTC by galiotoweb

## Description

Move the formatting for the list of members to it's own component instead of it all being in the members page file.
No styling was changed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation content changes
- [ ] Other (please describe)

## List any open issues this change will close
This closes #17

## Describe how to test/validate these changes
Build repo locally

## Screenshots (if appropriate)
![Screenshot 2020-10-24 members page](https://user-images.githubusercontent.com/10750369/97094106-b6b45180-161f-11eb-95e7-bc30ab8bae67.jpg)

2020-11-01 00:56 UTC, galiotoweb commented
Happy Halloween and Happy Hacktoberfest! 🎃 👩🏻‍💻

Tagging @alexxmitchell for a review

2020-11-01 14:17 UTC, alexxmitchell requested changes
As well please run `prettier --write "src/pages/members.js" "src/pages/membersItem.js"` in your terminal to format these files

2020-11-01 14:17 UTC, alexxmitchell commented on src/components/membersItem.js
> +      onError={(event) => { event.target.onerror = null; event.target.src = "https://avatars3.githubusercontent.com/u/13358086?s=200&v=4" }}
@galiotoweb Can you pull this out to a function similar to how it was before? It will help with readability

2020-11-01 17:33 UTC, galiotoweb commented
Moved the onError to its own line and formatted the files.

Prettier stopped working in my VS Code, and I didn't realize it, so thanks for the call out.

2020-11-04 00:24 UTC, alexxmitchell approved these changes
LGTM 👍

2020-11-04 00:25 UTC, merged